version: '3'
services: 
  airports:
    build: 
      context: ./airports
      dockerfile: "Dockerfile"
    image: dhlaluku/devops:airports
    ports: 
      - 8000:8000
    env_file: 
      - .env
    environment: 
      - APP_JAR=airports-assembly-1.0.1.jar

  countries:
    build: 
      context: ./countries
      dockerfile: "Dockerfile"
    image: dhlaluku/devops:countries
    ports: 
      - 8080:8080

  mynginx:
    build: 
      context: ./mynginx
      dockerfile: "Dockerfile"
    image: dhlaluku/devops:mynginx
    ports:
      - 80:80
      - 443:443
    links: 
      - airports
      - countries